### ISSUE TITLE
dynamic properties are deprecated

### ISSUE THREAD

**Issue by mweinbergh** [datadoit/ccs7up#1]
Since PHP Release 8.2 dynamic properties are deprecated and the logfile is filled with warnings. This patch adds the AllowDynamicProperties attribute to classes. See https://www.php.net/manual/de/class.allowdynamicproperties.php

Apply patch:
patch ccs7up.php ccs7up_AllowDynamicProperties.patch.txt

[ccs7up_AllowDynamicProperties.patch.txt](https://github.com/datadoit/ccs7up/files/12117031/ccs7up_AllowDynamicProperties.patch.txt)

**Comment by mwrathburn** [comment]
Updated. Thank you.

**Comment by mweinbergh** [comment]
Patch is not fully applied.
This part is missing:

@@ -225,7 +232,7 @@
 
     //Move our pointer to the next occurence (or end of file).
     $offset = $next_offset;
-    $str_result .= $string_to_process;
+    $str_result .= "$AllowDynamicProperties$string_to_process";
 
   } //end of while 'class' found
